### ISSUE TITLE
[feature request] disable solid background

### ISSUE THREAD

**Issue by FilipNone** [hacker1024/blur-enabler-magisk#1]
I'm using lineageos 21, android 14

please add the feature to remove the solid background that appears in front of the blur

you can see it better on the images:
![Screenshot_20240411-141255_Trebuchet](https://github.com/hacker1024/blur-enabler-magisk/assets/165696124/2277d301-7329-4871-a3ca-7683ff1f0d13)
blur

![Screenshot_20240411-141258_Trebuchet](https://github.com/hacker1024/blur-enabler-magisk/assets/165696124/8277aadb-3a78-4ac9-bc7b-67d08ca68b7e)
solid background

**Comment by hacker1024** [comment]
Unfortunately that requires modifying launcher code, and is outside the scope of this module.
